server:
    port: 8080
    servlet:
        jsp:
            init-parameters:
                development: true
spring:
    freemarker:
        cache: false
    devtools:
        add-properties: false
        livereload:
            enabled: true 
    mvc:
        static-path-pattern: /resources/**
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
logging:
    config: classpath:logback.xml

            # org.apache.jasper.servlet.TldScanner.level = FINE